# Generated by Django 3.1.3 on 2020-11-24 21:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_customer_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='taken_by',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
