# Generated by Django 3.1.3 on 2020-11-24 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20201124_2237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='transaction_id',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='date_ordered',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='date_addded',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='date_addded',
        ),
        migrations.AddField(
            model_name='order',
            name='date_complete',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
