# Generated by Django 3.1.3 on 2020-11-30 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_auto_20201130_1746'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductCategory',
            new_name='ProductCategories',
        ),
    ]
